<a href="https://colab.research.google.com/github/ppriyanshu26/Colab/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
# Import numpy
import numpy as np

In [34]:
# Creating arrays using list
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [35]:
# Dimensions of array
print("Dimension:",arr.ndim)

# Shape of array
print("Shape:",arr.shape)

# Size of array
print("Size:",arr.size)

# Data type of array
print("Data type:",arr.dtype)

Dimension: 1
Shape: (5,)
Size: 5
Data type: int64


In [36]:
# 2D Numpy Array
arr = np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [37]:
# Creating array using functions

print("Arange:\n",np.arange(1,10,2))

print("\nLinspace:\n",np.linspace(0,1,5))

print("\nZeros:\n",np.zeros((2,3)))

print("\nOnes:\n",np.ones((2,3)))

print("\nEye:\n",np.eye(3, dtype=int))

Arange:
 [1 3 5 7 9]

Linspace:
 [0.   0.25 0.5  0.75 1.  ]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Eye:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [38]:
# Indexing
a = np.array([[1,2,3],[4,5,6]])
print(a[0,2])

# Slicing
print(a[1,0:1])

3
[4]


In [39]:
#Arithmetic Operations

a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a**2)
print(b**3)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[1 4 9]
[ 64 125 216]


In [42]:
# Comparison Operationns

a = np.array([1,2,3])
print(a>1); print(a==1); print(a<1)

[False  True  True]
[ True False False]
[False False False]


In [46]:
# Universal Functions

print("\nSquare Root:\n",np.sqrt([1,4,9]))

print("\nExponential:\n",np.exp([1,2,3]))

print("\nSine Values:\n",np.sin([0, np.pi/2]))


Square Root:
 [1. 2. 3.]

Exponential:
 [ 2.71828183  7.3890561  20.08553692]

Sine Values:
 [0. 1.]


In [47]:
# Broadcasting

a = np.array([[1],[2],[3]])
b = np.array([4,5,6])
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [53]:
# Reshaping

a = np.array([[1,2],[3,4],[5,6]])
print(a.reshape(2,3))

# Flattening
print(a.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [57]:
# Statistics

a = np.array([[1,2,3],[4,5,6]])
print("Sum:",np.sum(a))

print("Max:",np.max(a))

print("Min:",np.min(a))

print("Mean:",np.mean(a))

print("Median:",np.median(a))

print("Variance:",np.var(a))

print("Standard Deviation:",np.std(a))

Sum: 21
Max: 6
Min: 1
Mean: 3.5
Median: 3.5
Variance: 2.9166666666666665
Standard Deviation: 1.707825127659933


In [58]:
# Dot product

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a.dot(b))

[[19 22]
 [43 50]]


In [82]:
# Random function

np.random.seed()
print(np.random.rand(3,4))
print()
print(np.random.randint(1,10,size=(5,4)))

[[0.65178023 0.71122749 0.62179936 0.64773114]
 [0.36877603 0.01631088 0.06065944 0.32410399]
 [0.88735606 0.60997521 0.82273793 0.00282336]]

[[9 5 2 2]
 [4 1 6 4]
 [5 9 9 8]
 [3 8 8 5]
 [5 7 9 9]]
