<a href="https://colab.research.google.com/github/ppriyanshu26/Colab/blob/main/Text%20Representation/BoW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Import modules

import spacy
from numpy import dot
import pandas as pd
from numpy.linalg import norm
from sklearn.feature_extraction.text import CountVectorizer

# Load spacy model
nlp = spacy.load('en_core_web_sm')

In [2]:
# Documents

doc1 = nlp("I like natural language processing.")
doc2 = nlp("Hi")

In [3]:
# Similarity
sim = dot(doc1.vector, doc2.vector)/(norm(doc1.vector)*norm(doc2.vector))
print(sim)

0.23092107


In [5]:
# Sentences

sentences = [
    "I love NLP",
    "NLP is fun",
    "I love coding"
]

In [6]:
# Vectorization

vect = CountVectorizer()
bow = vect.fit_transform(sentences)

print("Vocabulary:",vect.get_feature_names_out())
print("Bag of Words:\n",bow.toarray())

Vocabulary: ['coding' 'fun' 'is' 'love' 'nlp']
Bag of Words:
 [[0 0 0 1 1]
 [0 1 1 0 1]
 [1 0 0 1 0]]


In [8]:
# Dataframe

df = pd.DataFrame(bow.toarray(), columns=vect.get_feature_names_out())
print(df)

   coding  fun  is  love  nlp
0       0    0   0     1    1
1       0    1   1     0    1
2       1    0   0     1    0
